# Generated by Django 5.2.6 on 2025-09-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('university', 'University'), ('public', 'Public')], default='private', help_text='Project visibility level', max_length=20),
        ),
    ]
