# Generated by Django 5.2.6 on 2025-09-29 02:04

from django.db import migrations


def convert_cross_university_to_public(apps, schema_editor):
    """Convert any existing cross_university projects to public"""
    Project = apps.get_model('projects', 'Project')
    Project.objects.filter(visibility='cross_university').update(visibility='public')


def reverse_conversion(apps, schema_editor):
    """Reverse operation - not needed since we're removing the option"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_cross_university_visibility'),
    ]

    operations = [
        migrations.RunPython(convert_cross_university_to_public, reverse_conversion),
    ]
