# Generated by Django 5.1.6 on 2025-09-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_convert_cross_university_to_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='banner_gradient',
            field=models.CharField(default='sunrise', help_text='Identifier for the selected banner gradient', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Optional uploaded banner image', null=True, upload_to='project_banners/'),
        ),
        migrations.AddField(
            model_name='project',
            name='banner_style',
            field=models.CharField(choices=[('gradient', 'Gradient'), ('image', 'Image')], default='gradient', help_text='Display style for the project hero/banner', max_length=20),
        ),
    ]
