# Generated by Django 5.1.6 on 2025-10-04 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person submitting the inquiry', max_length=255)),
                ('email', models.EmailField(help_text='Email address for response', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('partnership', 'Partnership Opportunity'), ('university', 'University Partnership'), ('technical', 'Technical Support'), ('feedback', 'Feedback & Suggestions'), ('investor', 'Investor Relations'), ('press', 'Press & Media'), ('other', 'Other')], default='general', help_text='Type of inquiry', max_length=20)),
                ('subject', models.CharField(help_text='Subject of the inquiry', max_length=500)),
                ('message', models.TextField(help_text='Detailed message from the user')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', help_text='Current status of the inquiry', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the inquiry', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for staff (not visible to user)', null=True)),
                ('assigned_to', models.CharField(blank=True, help_text='Staff member assigned to handle this inquiry', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the submitter', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the inquiry was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the inquiry was last updated')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the inquiry was resolved', null=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='contact_con_created_1abdc3_idx'), models.Index(fields=['status'], name='contact_con_status_267d02_idx'), models.Index(fields=['inquiry_type'], name='contact_con_inquiry_8eb6f7_idx'), models.Index(fields=['priority'], name='contact_con_priorit_aa8435_idx'), models.Index(fields=['email'], name='contact_con_email_343558_idx')],
            },
        ),
    ]
