# Generated by Django 5.2.6 on 2025-09-17 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('user_role', models.CharField(choices=[('student', 'Student'), ('professor', 'Professor'), ('investor', 'Investor')], default='student', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself', max_length=1000, null=True)),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=100, null=True)),
                ('university', models.CharField(blank=True, help_text='Your university or institution', max_length=200, null=True)),
                ('major', models.CharField(blank=True, help_text='Field of study (for students)', max_length=100, null=True)),
                ('graduation_year', models.IntegerField(blank=True, help_text='Expected/actual graduation year', null=True)),
                ('department', models.CharField(blank=True, help_text='Department (for professors)', max_length=100, null=True)),
                ('research_interests', models.TextField(blank=True, help_text='Research areas of interest', max_length=500, null=True)),
                ('investment_focus', models.TextField(blank=True, help_text='Investment focus areas', max_length=500, null=True)),
                ('company', models.CharField(blank=True, help_text='Investment firm or company', max_length=200, null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL', null=True)),
                ('website_url', models.URLField(blank=True, help_text='Personal website URL', null=True)),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_profile_public', models.BooleanField(default=True, help_text='Make profile visible to other users')),
                ('show_email', models.BooleanField(default=False, help_text='Show email to other users')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
