# Generated by Django 5.2.6 on 2025-09-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banner_gradient',
            field=models.CharField(default='sunrise', help_text='Identifier for the selected banner gradient', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Optional uploaded banner image', null=True, upload_to='profile_banners/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banner_style',
            field=models.CharField(choices=[('gradient', 'Gradient'), ('image', 'Image')], default='gradient', help_text='Display style for the profile banner', max_length=20),
        ),
    ]
