# Generated by Django 5.2.6 on 2025-10-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text="Investor interests/categories (e.g., ['AI', 'Fintech', 'EdTech'])"),
        ),
    ]
