# Generated by Django 5.2.6 on 2026-04-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about yourself', max_length=500, null=True),
        ),
    ]
