# Generated by Django 5.1.6 on 2025-09-28 00:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Official university name', max_length=200, unique=True)),
                ('short_name', models.CharField(blank=True, help_text='Common abbreviation (e.g., MIT, UCLA)', max_length=50, null=True)),
                ('university_type', models.CharField(choices=[('public', 'Public University'), ('private', 'Private University'), ('community', 'Community College'), ('technical', 'Technical Institute'), ('other', 'Other')], default='public', help_text='Type of institution', max_length=20)),
                ('city', models.CharField(help_text='City where university is located', max_length=100)),
                ('state_province', models.CharField(help_text='State/Province', max_length=100)),
                ('country', models.CharField(help_text='Country', max_length=100)),
                ('website', models.URLField(blank=True, help_text='Official website', null=True)),
                ('email_domain', models.CharField(blank=True, help_text='Email domain for verification (e.g., mit.edu)', max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, help_text='University logo', null=True, upload_to='university_logos/')),
                ('description', models.TextField(blank=True, help_text='Brief description of the university', max_length=1000, null=True)),
                ('allow_cross_university_collaboration', models.BooleanField(default=True, help_text='Allow students from this university to see cross-university content')),
                ('feed_visibility_default', models.CharField(choices=[('university', 'University Only'), ('cross_university', 'Cross University'), ('public', 'Public')], default='university', help_text='Default visibility for content from this university', max_length=20)),
                ('student_count', models.PositiveIntegerField(default=0, help_text='Number of students from this university (auto-updated)')),
                ('professor_count', models.PositiveIntegerField(default=0, help_text='Number of professors from this university (auto-updated)')),
                ('project_count', models.PositiveIntegerField(default=0, help_text='Number of projects from this university (auto-updated)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='universitie_name_504812_idx'), models.Index(fields=['country', 'state_province'], name='universitie_country_6875ec_idx'), models.Index(fields=['email_domain'], name='universitie_email_d_7b2d1a_idx')],
            },
        ),
    ]
