# Generated by Django 5.1.6 on 2025-09-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='allow_cross_university_collaboration',
        ),
        migrations.RemoveField(
            model_name='university',
            name='feed_visibility_default',
        ),
    ]
